version: '2'
services:
  app:
    container_name: feedback-service
    image: feedback-service
    build: ./
    ports:
      - "8083:8083"
    depends_on:
      - db
  db:
    container_name: feedback-service_DB
    image: library/postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=comments